services:
  react-docker-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3013:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: react-docker-dev